SELECT
    SCHEDULE.SUBJECTCODE SUBJECTCODE,
    SCHEDULE.SUBJECT SUBJECT,
    SCHEDULE.TIMESLOT TIMESLOT,
    SCHEDULE.CLASSROOMNO CLASSROOMNO,
    SCHEDULE.CLASS CLASS
FROM
    SCHEDULE
WHERE
    UPPER(SCHEDULE.DAY)=TRIM((SELECT UPPER(TO_CHAR(SYSDATE, 'DAY')) FROM DUAL))
/