CREATE OR REPLACE VIEW DailyScheduleView
AS
SELECT 
    USERS.REGISTRATIONNO REGISTRATIONNO, 
    USERS.NAME NAME, 
    USERS.CLASS CLASS, 
    SCHEDULE.SUBJECTCODE SUBJECTCODE, 
    SCHEDULE.SUBJECT SUBJECT, 
    SCHEDULE.DAY DAY, 
    SCHEDULE.TIMESLOT TIMESLOT, 
    SCHEDULE.CLASSROOMNO CLASSROOMNO 
FROM 
    USERS, 
    SCHEDULE 
WHERE
    UPPER(USERS.CLASS)=UPPER(SCHEDULE.CLASS)
    AND UPPER(SCHEDULE.DAY)=TRIM((SELECT UPPER(TO_CHAR(SYSDATE, 'DAY')) FROM DUAL))
/
