CREATE OR REPLACE VIEW ExamScheduleView
AS
SELECT 
    USERS.REGISTRATIONNO REGISTRATIONNO, 
    USERS.NAME NAME, 
    USERS.CLASS CLASS, 
    SEATINGPLAN."Date" "Date", 
    SEATINGPLAN.SUBJECT SUBJECT, 
    SEATINGPLAN.TIMESLOT TIMESLOT, 
    SEATINGPLAN.CLASSROOMNO CLASSROOMNO
FROM 
    USERS, SEATINGPLAN 
WHERE
    USERS.REGISTRATIONNO=SEATINGPLAN.REGISTRATIONNO
    AND  TRIM(TO_CHAR(SEATINGPLAN."Date", 'DD-MON-YY'))=TRIM((SELECT TO_CHAR(SYSDATE, 'DD-MON-YY') FROM DUAL))
/