SELECT
    SEATINGPLAN.SUBJECT SUBJECT,
    SEATINGPLAN.TIMESLOT TIMESLOT,
    SEATINGPLAN.CLASSROOMNO CLASSROOMNO,
    SEATINGPLAN.REGISTRATIONNO REGISTRATIONNO 
FROM
    SEATINGPLAN
WHERE
    TRIM(TO_CHAR(SEATINGPLAN."Date", 'DD-MON-YY'))=TRIM((SELECT TO_CHAR(SYSDATE, 'DD-MON-YY') FROM DUAL))
/